<?php

namespace App\Entity\Repository;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Finds deleted character, will stop after 10 checks.
     *
     * @param $maxResults
     * @return array|mixed
     */
    public function findDeleted($maxResults)
    {
        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.deleted = 1')
            ->orderBy('c.lastUpdated', 'ASC')
            ->setMaxResults($maxResults)
            ->getQuery();

        return $qb->getResult();
    }

    /**
     * Find the total
     *
     * @return mixed
     */
    public function findTotal()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('count(c.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Find total with achievements
     *
     * @return mixed
     */
    public function findTotalWithAchievements()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->where('c.achievementsPrivate = 0');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
