<?php

namespace App\Entity\Repository;

/**
 * CharacterPendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterPendingRepository extends \Doctrine\ORM\EntityRepository
{
}
