<?php

namespace App\Entity\Repository;

/**
 * FreeCompanyPendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeCompanyPendingRepository extends \Doctrine\ORM\EntityRepository
{
}
