<?php

namespace App\Entity\Repository;

/**
 * LinkshellPendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkshellPendingRepository extends \Doctrine\ORM\EntityRepository
{
}
