<?php

namespace App\Entity\Repository;

/**
 * LinkshellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkshellRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the total
     *
     * @return mixed
     */
    public function findTotal()
    {
        $qb = $this->createQueryBuilder('ls')
            ->select('count(ls.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

}
