kupo:
  hostname:
  user: xivdb
  port: 22

monty:
  hostname:
  user: xivdb
  port: 22

noggy:
  hostname:
  user: xivdb
  port: 22

mosh:
  hostname:
  user: xivdb
  port: 22

mojito:
  hostname:
  user: xivdb
  port: 22

atla:
  hostname:
  user: xivdb
  port: 22

suzuna:
  hostname:
  user: xivdb
  port: 22

xivsync_home:
  hostname:
  user: xivdb
  port: 22

xivsync_characters_1:
  hostname:
  user: xivdb
  port: 22
