# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"

  # provision
  config.vm.provision :shell, path: "VagrantfileProvision.sh"

  # provider
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # high spec for data importing, realistically would be low
    vb.memory = 8000
    vb.cpus = 4
  end

  # network
  config.vm.network "private_network", ip: "4.4.4.4"

  # host domains
  config.vm.hostname = "xivdb.local"
  config.hostmanager.aliases = %w(
    fr.xivdb.local
    de.xivdb.local
    ja.xivdb.local
    ru.xivdb.local
    cn.xivdb.local
    kr.xivdb.local
    xivdb.adminer
    xivdb.kibana
    api.xivdb.local
    xivsync.local
    ms.tooltips.xivdb.local
    ms.maps.xivdb.local
    ms.data.xivdb.local
    ms.search.xivdb.local
    ms.pages.xivdb.local
    ms.email.xivdb.local
    ms.devapps.xivdb.local
    ms.comments.xivdb.local
    ms.screenshots.xivdb.local
    ms.translations.xivdb.local
    ms.feedback.xivdb.local
    ms.monitor.xivdb.local
    ms.mognet.xivdb.local
    ms.sync.xivdb.local
  )

  # host manager config
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  # sync folder
  config.vm.synced_folder ".", "/vagrant"
end
